[package]
name = "xrp-5usd-mm"
version = "0.1.0"
edition = "2021"

[workspace]

[lib]
name = "algo_xrp_usd"
crate-type = ["cdylib"]

[dependencies]
# Local development:
algo-sdk = { package = "sequence-algo-sdk", path = "../..", default-features = false }
# From crates.io:
# sequence-algo-sdk = { version = "0.1", default-features = false }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
